name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # TOMA EL CODIGO DEL REPOSITORIO
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # Git Semantic Version
    - name: Git Semantic Version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        major_pattern: "/major(\\(.+\\))?:/"
        minor_pattern: "/feat(\\(.+\\))?:/"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        bump_each_commit: true
      id: version

    # AUTENTICACION EN GITHUB
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    # Construccion de la imagen de docker
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t altamiranohernandezalan731/graphql-app:$NEW_VERSION .
        docker build -t altamiranohernandezalan731/graphql-app:latest .
    # Push de imagen de docker
    - name: Push Docker Image
      env: 
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push altamiranohernandezalan731/graphql-app:$NEW_VERSION
        docker push altamiranohernandezalan731/graphql-app:latest







        
