name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # TOMA EL CODIGO DEL REPOSITORIO
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # AUTENTICACION EN GITHUB
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    # Construccion de la imagen de docker
    - name: Build Docker Image
      run: |
        docker build -t altamiranohernandezalan731/graphql-app:0.0.2 .
        docker build -t altamiranohernandezalan731/graphql-app:latest .
    # Push de imagen de docker
    - name: Push Docker Image
      run: |
        docker push altamiranohernandezalan731/graphql-app:0.0.2
        docker push altamiranohernandezalan731/graphql-app:latest
